@startuml

skinparam linetype ortho

package "サイトマップ" {
  [ホーム] --> [予約システムトップ]
  [ホーム] --> [軽音楽部について]
  [ホーム] --> [お問い合わせ]

  [予約システムトップ] --> [ホーム]
  [軽音楽部について] --> [ホーム]
  [お問い合わせ] --> [ホーム]

  [予約システムトップ] --> ["予約システム 予定(週)"] : ログイン
  ["予約システム 予定(週)"] --> ["予約システム 自分の予定(週)"]
  ["予約システム 自分の予定(週)"] --> ["予約システム 予定(週)"]
  ["予約システム 予定(週)"] --> [予約システムトップ] : ログアウト
  ["予約システム 自分の予定(週)"] --> [予約システムトップ] : ログアウト
}

@enduml
